Repository Map-A-Droid/MAD, pull requests merged in 2019-10, with the labels that each got.

#450 Removed the db check to fix the stopsgyms update script
  scripts/update_stopsgyms.sh
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#458 API - Area tweaks
  madmin/api/apiHandler.py
  madmin/api/modules/ftr_area.py
  utils/data_manager.py
Labels: Status: Review Needed

#404 Display IV0 on madmin
  madmin/static/js/madmin.js
Labels: Type: Enhancement

#469 re-add the favicon
  madmin/templates/base.html
Labels: Type: Enhancement

#473 SQL strict mode sql_mode handling
  db/dbWrapperBase.py
  start.py
Labels: Type: Enhancement

#461 Show all stops on the madmin map
  db/rmWrapper.py
  madmin/routes/map.py
  madmin/static/js/madmin.js
  madmin/static/style/madmin.css
  madmin/templates/map.html
Labels: Type: Enhancement

#467 Api issues
  madmin/api/apiHandler.py
  madmin/api/apiRequest.py
  madmin/api/modules/ftr_walker.py
Labels: Type: Bug

#468 Rename Phonecontrol to Devicecontrol
  configs/config.ini.example
  madmin/api/modules/ftr_device.py
  madmin/api/modules/ftr_devicesetting.py
  madmin/functions.py
  madmin/routes/control.py
  madmin/static/vars/template/phone.tpl
  madmin/templates/base.html
  madmin/templates/settings_areas.html
  madmin/templates/settings_walkerarea.html
  utils/updater.py
  utils/walkerArgs.py
  worker/MITMBase.py
  worker/WorkerBase.py
Labels: Type: Enhancement

#476 Fix import and check for ADB support
  utils/adb.py
Labels: Type: Bug

#460 Add injection_thresh_reboot to device settings
  madmin/api/modules/ftr_device.py
Labels: Type: Enhancement
