Repository Map-A-Droid/MAD, pull requests merged in 2019-12, with the labels that each got.

#567 Fix "Last mon seen" in MAdmin
  madmin/static/js/madmin.js
Labels: Type: Bug

#572 Fix multi proxy and forwarded proxy
  madmin/madmin.py
Labels: Type: Enhancement

#553 Sort screentypes and detect bans
  ocr/pogoWindows.py
  ocr/screenPath.py
Labels: Type: Enhancement

#585 Attempt to disable vibration when starting pogo
  worker/WorkerBase.py
Labels: Type: Enhancement

#592 Init should have been default False per the code
  utils/data_manager/modules/area_mon_mitm.py
  utils/data_manager/modules/area_pokestops.py
  utils/data_manager/modules/area_raids_mitm.py
Labels: Type: Bug

#594 Added screendetection to device pools
  db/DbSchemaUpdater.py
  utils/data_manager/modules/devicepool.py
Labels: Type: Enhancement

#595 optimization of the /status page
  db/DbWrapper.py
  madmin/routes/statistics.py
  utils/MappingManager.py
Labels: Type: Bug, Type: Enhancement

#605 Updated trs_status.instance to int
  db/DbSchemaUpdater.py
  db/DbWrapper.py
  db/PooledQueryExecutor.py
  madmin/routes/statistics.py
  utils/version.py
  worker/MITMBase.py
  worker/WorkerBase.py
  worker/WorkerConfigmode.py
Labels: Type: Bug

#593 more quest conditions
  locale/de/LC_MESSAGES/quest.mo
  locale/de/LC_MESSAGES/quest.po
  locale/fr/LC_MESSAGES/quest.mo
  locale/fr/LC_MESSAGES/quest.po
  locale/quest.pot
  utils/questGen.py
Labels: Type: Enhancement

#613 fix routecalc so it doesnt save in memory mode
  utils/data_manager/modules/routecalc.py
Labels: Type: Bug

#621 add 0.163.0 32bit addresses
  configs/addresses.json
Labels: Type: Enhancement

#619 QoL updates
  madmin/api/__init__.py
  madmin/api/apiHandler.py
  madmin/api/modules/ftr_area.py
  madmin/madmin.py
  madmin/routes/config.py
  madmin/routes/control.py
  madmin/routes/map.py
  madmin/routes/statistics.py
  madmin/static/js/madmin.js
  madmin/templates/settings_areas.html
  mitm_receiver/MitmMapper.py
  mitm_receiver/PlayerStats.py
  route/RouteManagerBase.py
  route/routecalc/calculate_route_optimized.py
  route/routecalc/calculate_route_quick.py
  tests/api/test_geofences.py
  utils/MappingManager.py
  utils/data_manager/modules/device.py
  utils/data_manager/modules/geofence.py
  utils/data_manager/modules/resource.py
  utils/data_manager/modules/routecalc.py
  utils/version.py
  utils/walkerArgs.py
Labels: Type: Enhancement

#626 Multi thread job processing
  configs/config.ini.example
  utils/updater.py
  utils/walkerArgs.py
Labels: Type: Enhancement

#627 API now supports multi-instance deployments
  utils/data_manager/__init__.py
  utils/data_manager/modules/area.py
  utils/data_manager/modules/resource.py
Labels: Type: Enhancement

#617 New Instance Setup + Multi-Instance Conversion
  configmode.py
  db/PooledQueryExecutor.py
  start.py
  utils/convert_mapping.py
  utils/version.py
Labels: Type: Bug

#631 Minor API Restructuring
  madmin/api/__init__.py
  madmin/api/apiException.py
  madmin/api/apiHandler.py
  madmin/api/apiRequest.py
  madmin/api/modules/ftr_routecalc.py
  madmin/api/resources/__init__.py
  madmin/api/resources/ftr_area.py
  madmin/api/resources/ftr_auth.py
  madmin/api/resources/ftr_device.py
  madmin/api/resources/ftr_devicesetting.py
  madmin/api/resources/ftr_geofence.py
  madmin/api/resources/ftr_monlist.py
  madmin/api/resources/ftr_routecalc.py
  madmin/api/resources/ftr_walker.py
  madmin/api/resources/ftr_walkerarea.py
  madmin/api/resources/resourceHandler.py
  madmin/api/resources/resource_exceptions.py
  madmin/madmin.py
Labels: Type: Enhancement

#643 Routecalc in MADmin
  madmin/routes/config.py
  madmin/templates/settings_areas.html
  madmin/templates/settings_singleroutecalc.html
  tests/api/test_routecalc.py
  utils/data_manager/modules/routecalc.py
Labels: Type: Enhancement

#638 travis-ci
  .travis.yml
  configs/config.ini.travis
  configs/mappings.travis.json
  requirements.txt
  start.py
  tests/__init__.py
  tests/api/__init__.py
  tests/api/api_base.py
  tests/api/test_area.py
  tests/api/test_auth.py
  tests/api/test_device.py
  tests/api/test_devicesetting.py
  tests/api/test_geofences.py
  tests/api/test_monlist.py
  tests/api/test_routecalc.py
  tests/api/test_walker.py
  tests/api/test_walkerarea.py
  utils/walkerArgs.py
Labels: Type: Enhancement

#645 Add python3.7 to unit-testing
  .travis.yml
  requirements.txt
Labels: Type: Enhancement
