Repository Map-A-Droid/MAD, pull requests merged in 2020-01, with the labels that each got.

#639 Route calculation on startup is non-blocking
  route/RouteManagerBase.py
  utils/MappingManager.py
Labels: Type: Enhancement

#615 UX for route recalulation
  configmode.py
  db/DbWrapper.py
  db/PooledQueryExecutor.py
  db/madmin_conversion.py
  madmin/api/resources/ftr_area.py
  madmin/routes/config.py
  madmin/templates/settings_areas.html
  start.py
  utils/data_manager/__init__.py
  utils/data_manager/modules/area.py
  utils/data_manager/modules/resource.py
  utils/data_manager/modules/routecalc.py
Labels: Type: Enhancement

#653 Rotuecalc / GeoFence validation improvements
  utils/data_manager/modules/geofence.py
  utils/data_manager/modules/resource.py
  utils/data_manager/modules/routecalc.py
Labels: Type: Bug

#660 Refactor screen handling
  ocr/pogoWindows.py
  ocr/screenPath.py
  ocr/screen_type.py
  websocket/WebsocketServer.py
  worker/MITMBase.py
  worker/WorkerBase.py
  worker/WorkerQuests.py
Labels: Type: Bug, Type: Enhancement

#657 Fix: Config Option '-or' works with quick recalc
  start.py
Labels: Type: Bug

#610 prioQ fixes for mon_mitm, little improvements, logging
  db/DbWrapper.py
  db/madmin_conversion.py
  route/RouteManagerBase.py
  route/RouteManagerMon.py
  utils/data_manager/modules/area_mon_mitm.py
Labels: Type: Bug

#665 Add s2 cells for raid route coordinates
  madmin/routes/map.py
  madmin/static/js/madmin.js
  madmin/templates/map.html
Labels: Type: Enhancement

#652 move internal version from version.json to DB
  db/DbWrapper.py
  utils/version.py
Labels: Type: Enhancement

#683 Improved amount of device screens for higher resolutions
  madmin/templates/phonescreens.html
Labels: Type: Enhancement

#659 Initial development of MADmin hosted APKs
  commands.json
  configmode.py
  db/DbSanityCheck.py
  db/DbWrapper.py
  db/PooledQueryExecutor.py
  madmin/api/__init__.py
  madmin/api/apiHandler.py
  madmin/api/apiRequest.py
  madmin/api/apks/__init__.py
  madmin/api/apks/apkHandler.py
  madmin/api/apks/ftr_mad_apks.py
  madmin/api/global_variables.py
  madmin/functions.py
  madmin/madmin.py
  madmin/routes/apks.py
  madmin/templates/base.html
  madmin/templates/madmin_apk_root.html
  requirements.txt
  start.py
  utils/apk_util.py
  utils/global_variables.py
  utils/updater.py
  utils/version.py
  websocket/communicator.py
Labels: Type: Enhancement

#696 fix template formatting
  static/madmin/templates/change_gym.html
  static/madmin/templates/change_mon.html
  static/madmin/templates/change_raid.html
  static/madmin/templates/gyms.html
  static/madmin/templates/installation_status.html
  static/madmin/templates/madmin_apk_root.html
  static/madmin/templates/map.html
  static/madmin/templates/match_unknown.html
  static/madmin/templates/parser.html
  static/madmin/templates/phonescreens.html
  static/madmin/templates/quests.html
  static/madmin/templates/raids.html
  static/madmin/templates/screens.html
  static/madmin/templates/sel_type.html
  static/madmin/templates/settings.html
  static/madmin/templates/settings_areas.html
  static/madmin/templates/settings_auth.html
  static/madmin/templates/settings_devices.html
  static/madmin/templates/settings_geofences.html
  static/madmin/templates/settings_ivlists.html
  static/madmin/templates/settings_sharedsettings.html
  static/madmin/templates/settings_singlearea.html
  static/madmin/templates/settings_singleauth.html
  static/madmin/templates/settings_singledevice.html
  static/madmin/templates/settings_singlegeofence.html
  static/madmin/templates/settings_singleivlist.html
  static/madmin/templates/settings_singleroutecalc.html
  static/madmin/templates/settings_singlesharedsetting.html
  static/madmin/templates/settings_singlewalker.html
  static/madmin/templates/settings_walkerarea.html
  static/madmin/templates/settings_walkers.html
  static/madmin/templates/statistics.html
  static/madmin/templates/statistics/mon_statistics.html
  static/madmin/templates/statistics/shiny_statistics.html
  static/madmin/templates/statistics/spawn_statistics.html
  static/madmin/templates/statistics/statistics.html
  static/madmin/templates/statistics_worker.html
  static/madmin/templates/status.html
  static/madmin/templates/unknown.html
  static/madmin/templates/upload.html
  static/madmin/templates/uploaded_files.html
  static/madmin/templates/workerpicker.html
Labels: Type: Bug
