Repository Map-A-Droid/MAD, pull requests merged in 2020-11, with the labels that each got.

#1055 Add debug logging for data processing times
  mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
Labels: Type: Enhancement

#1039 Timezones fix
  mapadroid/db/DbWrapper.py
Labels: hacktoberfest-accepted

#1059 Make Travis happy
  mapadroid/mitm_receiver/SerializedMitmDataProcessor.py
Labels: Type: Bug

#1053 Add missing items names to items.json (and langs)
  locale/de/items.json
  locale/en/items.json
  locale/fr/items.json
  scripts/parse_items_for_items_json.py
Labels: Type: Enhancement

#1046 Fairer route splitting into subroutes
  mapadroid/route/RouteManagerBase.py
Labels: Type: Enhancement, hacktoberfest-accepted

#1026 Heatmap of non-IV's encounter
  mapadroid/db/DbStatsReader.py
  mapadroid/madmin/routes/statistics.py
  static/madmin/templates/statistics/mon_statistics.html
Labels: Type: Enhancement, hacktoberfest-accepted

#1034 Count up and restart on repeated spinnable check failures
  mapadroid/worker/WorkerQuests.py
Labels: Type: Enhancement, hacktoberfest-accepted
